# Generated by Django 4.1.5 on 2023-02-11 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingMaster',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HealthStatusDetails',
            fields=[
                ('health_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('product_healthy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('health_remarks', models.CharField(max_length=250)),
                ('product_status', models.CharField(choices=[('Working', 'Working'), ('Not Working', 'Not Working')], max_length=50)),
                ('status_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor', models.CharField(max_length=250)),
                ('roomno', models.CharField(max_length=250)),
                ('landmark', models.CharField(max_length=250)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryMaster',
            fields=[
                ('product_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('Consumable', 'Consumable'), ('Non-Consumable', 'Non-Consumable')], max_length=20, verbose_name='Product Type')),
                ('product_cat_name', models.CharField(max_length=250, verbose_name='Product Category Name :')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCompanyMaster',
            fields=[
                ('product_com_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_com_name', models.CharField(max_length=250, verbose_name='Product Company Name :')),
                ('product_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productcategorymaster')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('initial_quantity', models.IntegerField(default=1)),
                ('current_quantity', models.IntegerField(editable=False)),
                ('cartridge_toner', models.CharField(max_length=250)),
                ('remarks', models.CharField(max_length=300)),
                ('product_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productcategorymaster')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModelMaster',
            fields=[
                ('product_mod_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_mod_name', models.CharField(max_length=250, verbose_name='Product Model Name :')),
                ('product_com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productcompanymaster')),
            ],
        ),
        migrations.CreateModel(
            name='UserDesignationMaster',
            fields=[
                ('usr_des_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_des_name', models.CharField(max_length=250)),
                ('usr_des_type', models.CharField(choices=[('Judge', 'Judge'), ('Staff', 'Staff')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=250)),
                ('usr_mobile', models.CharField(max_length=250)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.locationdetails')),
                ('usr_des_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userdesignationmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_tpye', models.CharField(choices=[('Issued', 'Issued'), ('AtComputerSection', 'At Computer Section')], max_length=50)),
                ('trans_date', models.DateField()),
                ('no_of_item', models.IntegerField()),
                ('remarks', models.CharField(max_length=250)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.locationdetails')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productdetails')),
                ('usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='SectionDetails',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('Court', 'Court'), ('Section', 'Section')], max_length=10)),
                ('section_name', models.CharField(max_length=250)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.buildingmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSerialMaster',
            fields=[
                ('product_ser_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_serial_number', models.CharField(max_length=250, verbose_name='Product Model Name :')),
                ('product_mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmodelmaster')),
            ],
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmodelmaster'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productcompanymaster'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_serialno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productserialmaster'),
        ),
        migrations.AddField(
            model_name='locationdetails',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sectiondetails'),
        ),
    ]
