# Generated by Django 4.1.5 on 2023-03-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='location_id',
        ),
    ]
