# Generated by Django 4.1.5 on 2023-03-15 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_userdetails_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.locationdetails'),
        ),
    ]
