# Generated by Django 4.1.5 on 2023-02-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=250)),
                ('usr_mobile', models.CharField(max_length=250)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.locationdetails')),
            ],
        ),
        migrations.RenameField(
            model_name='userdesignationmaster',
            old_name='emp_des_id',
            new_name='usr_des_id',
        ),
        migrations.RenameField(
            model_name='userdesignationmaster',
            old_name='emp_des_name',
            new_name='usr_des_name',
        ),
        migrations.RenameField(
            model_name='userdesignationmaster',
            old_name='emp_des_type',
            new_name='usr_des_type',
        ),
        migrations.RemoveField(
            model_name='transactiondetails',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='cartridge_toner',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='current_quantity',
            field=models.IntegerField(editable=False),
        ),
        migrations.RenameModel(
            old_name='EmployeeDesignationMaster',
            new_name='UserDesignationMaster',
        ),
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='usr_des_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userdesignationmaster'),
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='usr_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.userdetails'),
            preserve_default=False,
        ),
    ]
